Build against Qt6.
sailfishos/nemo-qml-plugin-notifications pull request #8
Opened 2023-05-30 12:45 UTC by mkosola

2023-05-30 12:48 UTC, mkosola commented
Ah, need to add ifdef to build properly

2023-05-30 12:50 UTC, Tomin1 requested changes
This needs ifdefs.

2023-05-30 12:50 UTC, Tomin1 commented on src/notification.cpp
> +    argument << QByteArray(reinterpret_cast<const char *>(image.bits()), image.sizeInBytes());
Doesn't exist in Qt 5.6.

https://doc.qt.io/qt-5/qimage.html#sizeInBytes

2023-05-30 12:50 UTC, Tomin1 commented on src/notification.cpp
> +            QStringList elements(hint.split(' ', Qt::SkipEmptyParts));
Doesn't exist in Qt 5.6.

https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum

2023-05-30 13:01 UTC, Tomin1 reviewed
Looks better. I'm wondering about the version numbers though since those were introduced already before 6.0.

2023-05-30 13:01 UTC, Tomin1 commented on src/notification.cpp
> +#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
Should we have `5, 10, 0` instead of `6, 0, 0` though?

2023-05-30 13:01 UTC, Tomin1 commented on src/notification.cpp
> +#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
Should we have `5, 14, 0` instead of `6, 0, 0` though?

2023-05-30 13:17 UTC, Tomin1 approved these changes

2023-06-06 12:55 UTC, pvuorela approved these changes

2023-06-06 13:08 UTC, merged